@startuml
class Procesos.Ejercicio1.BibliotecaProceso {
}
class Procesos.Ejercicio1.BibliotecaProceso$EstadisticaBiblioteca {
+ {static} double calcularPromedioPalabras(List<Libro>)
+ {static} int contarFavoritos(Usuario)
}

class Procesos.Ejercicio1.LibroProceso {
+ {static} int calcularPalabrasEstimadas(Libro)
+ {static} int calcularPalabrasEstimadas(Libro,int,int)
}

class Procesos.Ejercicio1.AppBiblioteca {
+ {static} void main(String[])
- {static} void mostrarResultados(List<Libro>)
- {static} void registrarPublicacion(Scanner,Biblioteca)
- {static} List<Libro> generarLibrosDePrueba()
- {static} List<Revista> generarRevistasDePrueba()
- {static} void mostrarRevistas(List<Revista>)
- {static} void mostrarPublicacionesDisponibles(Biblioteca)
}

class Procesos.Ejercicio1.UsuarioProceso {
+ {static} List<Libro> buscarPorTitulo(Biblioteca,String)
+ {static} List<Libro> buscarPorAutor(Biblioteca,String)
+ {static} List<Revista> buscarRevistaPorTitulo(Biblioteca,String)
+ {static} List<Revista> buscarRevistaPorAutor(Biblioteca,String)
+ {static} void marcarComoFavorito(Usuario,Libro)
+ {static} void marcarRevistaComoFavorita(Usuario,Revista)
}



Procesos.Ejercicio1.BibliotecaProceso +.. Procesos.Ejercicio1.BibliotecaProceso$EstadisticaBiblioteca
@enduml